drop table if exists member CASCADE;
create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);

수정 2020-09-23 18시
drop table if exists member;
CREATE TABLE `member`(
    `id` int(11) not null,
    `name` char(20) default null,
    primary key(`id`)
) engine=innodb default charset=utf8;